<!DOCTYPE html>
<html>
<head>
<title></title>
<meta name="description" content="">
<style type="text/css">/* Caratteristiche generali del corpo della pagina */
body {
 margin: 0;
 padding: 0;
 background-color: #FFF;
 font-family: arial, verdana, sans-serif;
 color: #000;
}
/* caratteristiche del contenitore del codice HTML */
.container {
 width: 80%;
 margin: 0 auto;
}</style>
</head>
<body>
<div class="container">
<p style="text-align: center;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://irvin.redemptorismatercosenza.com/doc_hub/1016_Ant.-Magn.-25-dic.png" alt="" width="353.5" height="500" /><a href="https://www.redemptorismatercosenza.com/donazioni/it-IT">Donare</a></p>
</div>
</body>
</html>
